# Generated by Django 4.2.6 on 2023-10-29 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='automovil',
            new_name='Auto',
        ),
    ]
